import { OpenAI, toFile } from 'openai';
import { hasKv, kvGet, kvIncr, kvExpire } from '@/lib/kv';

export const runtime = 'nodejs';        // required — OpenAI SDK uses Node APIs
export const maxDuration = 180;         // gpt-image-2 high-quality edit takes 60-120s

const DAILY_CAP = 10;                   // per IP per day

export async function POST(request) {
  // Rate limiting disabled — re-enable before public launch

  // 1. Parse multipart body
  let formData;
  try { formData = await request.formData(); }
  catch { return Response.json({ ok: false, error: 'invalid' }, { status: 400 }); }

  // NOTE: no API mask. With images.edit a masked region is REMOVED and regenerated
  // blind — the model never sees the car inside it and substitutes a different
  // vehicle (verified empirically: BMW M3 in → Supra/Golf out). Instead the model
  // receives the full unmasked composite so it can preserve the actual car, and
  // the CLIENT re-composites the original bay outside the car region afterwards,
  // which guarantees the exact studio background.
  const imageFile = formData.get('image');       // 1536×1024 composite: car already placed in the M&C studio bay
  const swatchFile = formData.get('swatch');     // solid-colour reference PNG of the exact wrap colour
  const finish = String(formData.get('finish') || 'gloss');
  const colourName = String(formData.get('colourName') || 'wrap');
  const colourHex = String(formData.get('colourHex') || '');
  if (!imageFile || typeof imageFile === 'string') {
    return Response.json({ ok: false, error: 'no_image' }, { status: 400 });
  }

  const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

  const composite = await toFile(
    Buffer.from(await imageFile.arrayBuffer()), 'composite.png', { type: 'image/png' });
  const swatch = (swatchFile && typeof swatchFile !== 'string')
    ? await toFile(Buffer.from(await swatchFile.arrayBuffer()), 'swatch.png', { type: 'image/png' })
    : undefined;

  // Prompt strategy:
  //  - The car arrives in its ORIGINAL paint, composited into the studio bay. The
  //    original photo carries the identity cues (grille, badges, body lines) the
  //    model needs to keep it the exact same vehicle — a pre-recoloured car loses
  //    them and the model substitutes a different car.
  //  - The studio bay in the output is regenerated by the model, but the client
  //    re-composites the original bay outside the car region after the render,
  //    guaranteeing the background is pixel-exact regardless of model drift.
  //  - The swatch reference image + exact hex in the prompt pin the wrap colour.
  const finishDesc = {
    gloss: 'high-gloss vinyl wrap — deep wet-look shine, crisp soft-box reflections following the body lines',
    satin: 'satin vinyl wrap — smooth semi-sheen, soft diffused highlights, no mirror reflections',
    matte: 'matte vinyl wrap — completely flat non-reflective surface, velvety light falloff, zero specular highlights',
    metallic: 'metallic vinyl wrap — fine metal-flake sparkle visible in the highlights, bright sheen on curved panels',
    carbon: 'carbon-fibre vinyl wrap — visible fine 2x2 carbon weave texture across the panels, semi-gloss',
    chrome: 'mirror chrome vinyl wrap — fully mirrored surface reflecting the studio environment',
    shift: 'colour-shift (flip) vinyl wrap — iridescent paint that shifts hue across panels depending on the angle to the light',
    'ppf-clear': 'gloss paint-protection film over the original paint — enhanced clarity and shine, colour unchanged',
    'ppf-matte': 'matte paint-protection film over the original paint — flat satin sheen, colour unchanged',
  }[finish] || 'vinyl wrap';

  const colourClause = colourHex
    ? `The wrap colour is EXACTLY ${colourHex} ("${colourName}")` +
      (swatch ? ' — the second reference image is a physical sample of this exact colour; match it precisely.' : '.')
    : `The wrap is "${colourName}".`;

  const jobClause =
    `Re-wrap ONLY the painted body panels of this exact car (bonnet, roof, doors, wings, bumpers, boot, sills, mirror caps) ` +
    `in a ${finishDesc}. ${colourClause} Every panel must be the identical colour — perfectly uniform coverage. ` +
    `Do not wrap the glass, lights, grille mesh, badges, number plate, tyres or wheels — leave them exactly as photographed.`;

  const prompt =
    `Professional automotive studio photograph, shot in the workshop bay shown — the scene and camera must not change. ` +
    `${jobClause} ` +
    `CRITICAL — this is a real customer's car: preserve its exact make, model, body shape, proportions, stance, ride height, ` +
    `wheel design, glass, headlights, grille, badges and number plate. Every panel gap and body line must match the photo. ` +
    `It must remain instantly recognisable as the very same vehicle, changed ONLY in wrap colour and finish. ` +
    `Integrate the car into the bay: studio soft-box lighting falling on the body consistent with the bay's overhead lights, ` +
    `a soft contact shadow under the tyres, and a subtle reflection of the car on the polished floor. ` +
    `Do NOT move, rescale or rotate the car. Do NOT alter the background, walls, floor or signage. Photorealistic, sharp focus.`;

  let result;
  try {
    result = await client.images.edit({
      model: 'gpt-image-2',     // snapshot gpt-image-2-2026-04-21 — processes inputs at high fidelity automatically
      image: swatch ? [composite, swatch] : composite,
      prompt,
      size: '1536x1024',        // landscape — matches stage aspect ratio
      quality: 'high',
      n: 1,
    });
  } catch (err) {
    const msg = err?.message || String(err);
    const status = err?.status || err?.statusCode || '?';
    console.error('[wrap-render][openai-error]', status, msg, JSON.stringify(err?.error || ''));
    return Response.json({ ok: false, error: 'api_error', detail: msg }, { status: 500 });
  }

  // Return as data URL
  const b64 = result.data[0].b64_json;
  return Response.json({ ok: true, renderUrl: `data:image/png;base64,${b64}` });
}
